spring:
  datasource:
    url: jdbc:mysql://173.212.205.55:3306/yingshi?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: yingshi
    password: yingshi  #数据库名、用户名和密码改为自己的
    driver-class-name: com.mysql.cj.jdbc.Driver

url: mm.sharegd.xyz/3:/
user: xiaobai
passwd: 777
